apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: web-server
          image: php:8.2-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www-data
              mountPath: /var/www/html
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update && apt-get install -y git libzip-dev unzip;
              docker-php-ext-install pdo pdo_mysql zip;
              if [ ! -d /var/www/html/.git ]; then
                git clone -b master https://github.com/PhengMenghour/devops-exam.git /tmp/app;
                cp -r /tmp/app/* /var/www/html/;
                rm -rf /tmp/app;
              fi;
              chown -R www-data:www-data /var/www/html;
              chmod -R 755 /var/www/html;
              a2enmod rewrite;
              echo '<VirtualHost *:80>
                DocumentRoot /var/www/html/public
                <Directory /var/www/html/public>
                  AllowOverride All
                  Require all granted
                </Directory>
              </VirtualHost>' > /etc/apache2/sites-available/000-default.conf;
              apache2-foreground
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 30
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Hello@123"
            - name: MYSQL_DATABASE
              value: "menghour-db"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: www-data
          emptyDir: {}
        - name: mysql-data
          emptyDir: {}