apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30306
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022
